### ISSUE TITLE
NEW] Ajouter make release, en utilisant une fonction pour recrerr https://github.com/InriaMecsci/snappy/releases

### ISSUE THREAD

**Issue by vthierry** [InriaMecsci/snappy#2]
Le makefile permet de generer le site web etc et de propager un patch sans faire de fausse manip avec toutes les commandes
Pouvoir aussi regerenerer cette partie de la distrib serait bien utile pour la maintenance

**Comment by benyemna** [comment]
les regles git-attributes ont ete cree ainsi que la regle "release" dans le makefile
