### ISSUE TITLE
creation login

### ISSUE THREAD

**Issue by oceank2** [InriaMecsci/snappy#3]
Je souhaitais me créér un compte mais j'obtiens un message comme quoi la connexion au cloud est impossible. Cette fonctionnalité n'est peut-être pas encore active ?

**Comment by vthierry** [comment]
effectivement comme tu le montres ici  https://youtu.be/H9qR7qgg8KM snappy a garder une fonctionnalite obsolete de s inscrire sur Snap (elle marche bien sur http://snap.berkeley.edu/run mais je ne vois pas trop son utilite car la communaute est moins active que scratch)
-> ma proposition : retirer ce boutin qui cree de la confusion , ok ?

**Comment by oceank2** [comment]
pas de soucis
OK pour moi

**Comment by vthierry** [comment]
> Après pour le "cloud" snap propose-t-il comme dans scratch d'avoir des variables partagées dans un cloud ? Si oui, l'accès à ces variables n'est possible qu'en mode connecté. C'est une fonctionnalité super intéressante , par exemple pour faire un chat en réseau,etc
me dit oceank2 par mail, 

@Ramzy qu'en penses tu ?

**Comment by oceank2** [comment]
Je viens de tester sous snap et la fonctionnalité dont je parlais qui 
existe sous Scratch n'existe pas (encore) sous snap :'(
Donc pour le moment je pense qu'il n'y a pas de soucis pour désactiver 
cette fonctionnalité

**Comment by vthierry** [comment]
Donc a l unaminite on dit : Ramzy : fait disparaitre le bouton avec le petit nuage qui cree de la confusion,
merci à toi oceank2

**Comment by benyemna** [comment]
Effectivement je pense qu'on doit la cacher et la laisser dans le code pour le futur. 
@vthierry t'as taggé une autre personne dans ta réponse :p mon pseudo est: @benyemna
