### ISSUE TITLE
Outil de transparence

### ISSUE THREAD

**Issue by oceank2** [InriaMecsci/snappy#4]
Sauf erreur si l'on souhaite rendre le fond d'une image de lutin  transparente il n'y a pas possibilité de la faire comme sous Scratch avec l'outil pot de peinture. C'est vraiment dommage car cela est vraiment très pratique.
Cordialement

**Comment by vthierry** [comment]
> la couleur de remplissage "transparent" existe bien dans l'outil sauf quelle est quelque peu cachée 

oui tu as raison c'est en bas à droit de la palette des couleurs la zone avec un damier gris et noir
